#!/bin/bash

based=$(dirname $0)/..
pname=$(basename $0)
stime=$(date +%Y%m%d%H%M%S%Z)

msg(){
    echo "$pname $stime $(date +%Y%m%d%H%M%S%Z) $@"	>&2
}

tmp=/tmp/$pname.$stime.$$
if ! mkdir $tmp ; then
    msg ERROR can not make temporally directory.
    exit 1
fi
trap 'rm -rf $tmp' EXIT
################################################################

ls $based/cloud-res/*/terraform.tfstate	|
    xargs -n1 dirname	|
    while read dir ; do
	pushd $dir	> /dev/null

	terraform refresh
	terraform show -no-color	|
	    grep -A1 -E '^aws_.+:$'	|
	    grep -v '^--$'		|
	    xargs -n4			|
	    cut -d' ' -f1,4		|
	    sed 's/: / /'		|
	    LANG=C sort	> resource_id.lst

	popd		> /dev/null
    done

################################################################
exit 0
